# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Natomic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CHIPageControl'
  pod 'IQKeyboardManagerSwift'
  pod 'FittedSheets'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseAnalytics'
  pod 'GoogleSignIn'
  pod 'Alamofire'
  pod 'NVActivityIndicatorView'
  pod 'SDWebImage'
  # Pods for Natomic

  # Set the deployment target for your target
  platform :ios, '13.0'

  # You can also set build settings here if needed for your own target
  # For example:
  # build_settings['SWIFT_VERSION'] = '5.0'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
