# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Natomic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CHIPageControl'
  pod 'IQKeyboardManagerSwift'
  # Pods for Natomic

end
